version: '2'

services:
 guacamole-client:
  extends:
   file: ./docker-compose.yml
   service: guacamole-client

 guacamole-server:
  extends:
   file: ./docker-compose.yml
   service: guacamole-server

 nanocloud-backend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-backend
  volumes_from:
   - nanocloud-frontend
   - nanocloud-canva

 nanocloud-frontend:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-frontend
  volumes:
   - /opt/front
  container_name: "nanocloud-frontend"

 nanocloud-canva:
  extends:
   file: ./docker-compose.yml
   service: nanocloud-canva
  volumes:
   - /opt/canva
  container_name: "nanocloud-canva"

 proxy:
  extends:
   file: ./docker-compose.yml
   service: proxy

 postgres:
  extends:
   file: ./docker-compose.yml
   service: postgres

 iaas-module:
  extends:
   file: ./docker-compose.yml
   service: iaas-module

networks:
 nanocloud:
  driver: bridge
