guacamole-client:
 extends:
  file: ./docker-compose.yml
  service: guacamole-client

guacamole-server:
 extends:
  file: ./docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-backend
 volumes_from:
  - nanocloud-frontend

nanocloud-frontend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-frontend
 volumes:
  - /opt/front
 build: ../webapp
 dockerfile: Dockerfile-dev
 volumes:
  - ../webapp/:/opt/front
 restart: always
 container_name: "nanocloud-frontend"

proxy:
 extends:
  file: ./docker-compose.yml
  service: proxy

rabbitmq:
 extends:
  file: ./docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./docker-compose.yml
  service: postgres

iaas-module:
 extends:
  file: ./docker-compose.yml
  service: iaas-module
 build: ./iaas
 dockerfile: Dockerfile-dev
 volumes:
  - ./iaas/:/go/src/github.com/Nanocloud/community/modules/iaas/
