version: '2'

services:
 guacamole-client:
  restart: always
  container_name: "guacamole-client"
  networks:
   - nanocloud

 nanocloud-backend:
  environment:
   - ADMIN_PASSWORD=admin
   - ENV=production
   - EXECUTION_SERVERS=iaas-module
   - IAAS=qemu
   - LDAP_OU=OU=NanocloudUsers,DC=intra,DC=localdomain,DC=com"
   - LDAP_PASSWORD=Nanocloud123+
   - LDAP_SERVER_URI=ldaps://Administrator:Nanocloud123+@iaas-module:6360
   - LDAP_USERNAME=CN=Administrator,CN=Users,DC=intra,DC=localdomain,DC=com
   - PLAZA_ADDRESS=iaas-module
   - WINDOWS_DOMAIN=intra.localdomain.com
   - WINDOWS_PASSWORD=Nanocloud123+
   - WINDOWS_USER=Administrator
  restart: always
  container_name: "nanocloud-api"
  networks:
   - nanocloud

 guacamole-server:
  restart: always
  container_name: "guacamole-server"
  networks:
   - nanocloud

 nanocloud-frontend:
  container_name: "nanocloud-webapp"
  volumes:
   - /opt/front
  networks:
   - nanocloud

 proxy:
  restart: always
  container_name: "proxy"
  networks:
   - nanocloud

 postgres:
  image: postgres:9.5
  environment:
   - PGDATA=/var/lib/postgresql/data/pgdata
   - POSTGRES_USER=nanocloud
  restart: always
  container_name: "postgres"
  networks:
   - nanocloud

 iaas-module:
  environment:
   - ENV=production
   - SSH_PORT=1119
   - ARTIFACT_URL=http://releases.nanocloud.org:8080/releases/0.7.0/
  devices:
   - /dev/kvm
  restart: always
  container_name: "iaas-module"
  networks:
   - nanocloud

networks:
 nanocloud:
  driver: bridge
