guacamole-client:
 extends:
  file: ./docker-compose.yml
  service: guacamole-client
 build: ./canva/guacamole-client
 dockerfile: Dockerfile-dev
 ports:
  - 8000:8000
 volumes:
  - ./canva/guacamole-client/:/opt
  - ./canva/guacamole-client/noauth-logged/target/guacamole-auth-noauthlogged-0.9.8.jar:/etc/guacamole/extensions/guacamole-auth-noauthlogged-0.9.8.jar

guacamole-server:
 extends:
  file: ./docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-backend
 build: ../nanocloud
 dockerfile: Dockerfile-dev
 volumes_from:
  - nanocloud-frontend
 volumes:
  - ../nanocloud:/go/src/github.com/Nanocloud/community/nanocloud/

nanocloud-frontend:
 extends:
  file: ./docker-compose.yml
  service: nanocloud-frontend
 volumes:
  - /opt/front
 build: ../webapp
 dockerfile: Dockerfile-dev
 volumes:
  - ../webapp/:/opt/front
 restart: always
 container_name: "nanocloud-frontend"

proxy:
 extends:
  file: ./docker-compose.yml
  service: proxy

rabbitmq:
 extends:
  file: ./docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./docker-compose.yml
  service: postgres

iaas-module:
 extends:
  file: ./docker-compose.yml
  service: iaas-module
 build: ./iaas
 dockerfile: Dockerfile-dev
 volumes:
  - ./iaas/:/go/src/github.com/Nanocloud/community/modules/iaas/
