guacamole-client:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: guacamole-client
 image: nanocloud/guacamole-client

guacamole-server:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: nanocloud-backend
 image: nanocloud/nanocloud-backend

proxy:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: proxy

ambassador:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: ambassador

rabbitmq:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: postgres

apps-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: apps-module
 image: nanocloud/apps-module

history-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: history-module
 image: nanocloud/history-module

iaas-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: iaas-module
 image: nanocloud/iaas-module

apiiaas-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: apiiaas-module
 image: nanocloud/apiiaas-module

ldap-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: ldap-module
 image: nanocloud/ldap-module

users-module:
 extends:
  file: ./dockerfiles/docker-compose.yml
  service: users-module
 image: nanocloud/users-module
