guacamole-client:
 extends:
  file: ./modules/docker-compose.yml
  service: guacamole-client
 image: nanocloud/guacamole-client:indiana

guacamole-server:
 extends:
  file: ./modules/docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./modules/docker-compose.yml
  service: nanocloud-backend
 image: nanocloud/nanocloud-backend:indiana
 volumes_from:
  - nanocloud-frontend

nanocloud-frontend:
 extends:
  file: ./modules/docker-compose.yml
  service: nanocloud-backend
 image: nanocloud/nanocloud-frontend:indiana
 container_name: "nanocloud-frontend"
 volumes:
  - /opt/front

proxy:
 extends:
  file: ./modules/docker-compose.yml
  service: proxy

rabbitmq:
 extends:
  file: ./modules/docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./modules/docker-compose.yml
  service: postgres

iaas-module:
 extends:
  file: ./modules/docker-compose.yml
  service: iaas-module
 image: nanocloud/iaas-module:indiana
