guacamole-client:
 extends:
  file: ./modules/docker-compose.yml
  service: guacamole-client
 image: nanocloud/guacamole-client:0.3.1

guacamole-server:
 extends:
  file: ./modules/docker-compose.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./modules/docker-compose.yml
  service: nanocloud-backend
 volumes_from:
  - nanocloud-frontend
 image: nanocloud/nanocloud-backend:0.3.1

nanocloud-frontend:
 extends:
  file: ./modules/docker-compose.yml
  service: nanocloud-backend
 container_name: "nanocloud-frontend"
 volumes:
  - /opt/front
 image: nanocloud/nanocloud-frontend:0.3.1

proxy:
 extends:
  file: ./modules/docker-compose.yml
  service: proxy

rabbitmq:
 extends:
  file: ./modules/docker-compose.yml
  service: rabbitmq

postgres:
 extends:
  file: ./modules/docker-compose.yml
  service: postgres

iaas-module:
 extends:
  file: ./modules/docker-compose.yml
  service: iaas-module
 image: nanocloud/iaas-module:0.3.1
