guacamole-client:
 extends:
  file: ./modules/docker-compose-build.yml
  service: guacamole-client
 image: nanocloud/guacamole-client:0.2

guacamole-server:
 extends:
  file: ./modules/docker-compose-build.yml
  service: guacamole-server

nanocloud-backend:
 extends:
  file: ./modules/docker-compose-build.yml
  service: nanocloud-backend
 image: nanocloud/nanocloud-backend:0.2
 volumes_from:
  - nanocloud-frontend

nanocloud-frontend:
 extends:
  file: ./modules/docker-compose-build.yml
  service: nanocloud-backend
 image: nanocloud/nanocloud-frontend:0.2
 container_name: "nanocloud-frontend"
 volumes:
  - /opt/front

proxy:
 extends:
  file: ./modules/docker-compose-build.yml
  service: proxy

rabbitmq:
 extends:
  file: ./modules/docker-compose-build.yml
  service: rabbitmq

postgres:
 extends:
  file: ./modules/docker-compose-build.yml
  service: postgres

apps-module:
 extends:
  file: ./modules/docker-compose-build.yml
  service: apps-module
 image: nanocloud/apps-module:0.2

history-module:
 extends:
  file: ./modules/docker-compose-build.yml
  service: history-module
 image: nanocloud/history-module:0.2

iaas-module:
 extends:
  file: ./modules/docker-compose-build.yml
  service: iaas-module
 image: nanocloud/iaas-module:0.2

ldap-module:
 extends:
  file: ./modules/docker-compose-build.yml
  service: ldap-module
 image: nanocloud/ldap-module:0.2

users-module:
 extends:
  file: ./modules/docker-compose-build.yml
  service: users-module
 image: nanocloud/users-module:0.2
