guacamole-client:
 build: ./
 dockerfile: guacamole-client/Dockerfile
 volumes:
  - ./guacamole-client/guac_home/guacamole.properties:/etc/guacamole/guacamole.properties
  - ./guacamole-client/guac_home/noauth-config.xml:/etc/guacamole/noauth-config.xml
 restart: always
 container_name: "guacamole-client"

guacamole-server:
 image: glyptodon/guacd:0.9.8
 restart: always
 container_name: "guacamole-server"

nanocloud-backend:
 build: ./
 dockerfile: Dockerfile-nanocloud
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - DATABASE_URI=postgres://nanocloud@postgres/nanocloud?sslmode=disable
  - PORT=8080
  - FRONT_DIR=front/
  - WIN_PASSWORD=Nanocloud123+
  - WIN_PORT=1119
  - WIN_USER=Administrator
  - WIN_SERVER=10.0.2.2
 volumes:
  - ./guacamole-client/guac_home/noauth-config.xml:/opt/conf/noauth.xml
 volumes_from:
  - guacamole-client
 restart: always
 container_name: "nanocloud-api"

proxy:
 image: nginx:1.9
 volumes:
  - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  - ./nginx/conf/certificates:/etc/nginx/ssl/:ro
 ports:
  - 80:80
  - 443:443
 restart: always
 container_name: "proxy"

ambassador:
 image: cpuguy83/docker-grand-ambassador:0.9.1
 volumes:
 - "/var/run/docker.sock:/var/run/docker.sock"
 command: "-name dockerfiles_guacamole-client_1 -name dockerfiles_proxy_1 "
 restart: always
 container_name: "ambassador"

rabbitmq:
 image: rabbitmq:3.5
 restart: always
 container_name: "rabbitmq"

postgres:
 image: postgres:9.4
 volumes:
  - ./postgres:/var/lib/postgresql/data/pgdata
 environment:
  - PGDATA=/var/lib/postgresql/data/pgdata
  - POSTGRES_USER=nanocloud
 restart: always
 container_name: "postgres"

apps-module:
 dockerfile: Dockerfile-apps
 build: .
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - USER=Administrator
  - SSH_PORT=1119
  - RDP_PORT=3389
  - SERVER=10.20.12.20
  - PASSWORD=Nanocloud123+
  - XML_CONFIGURATION_FILE=/opt/conf/noauth.xml
  - WINDOWS_DOMAIN=intra.localdomain.com
  - EXECUTION_SERVERS=10.20.12.20
 restart: always
 volumes:
  - ./guacamole-client/guac_home/noauth-config.xml:/opt/conf/noauth.xml
 container_name: "apps-module"

history-module:
 dockerfile: Dockerfile-history
 build: .
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - DATABASE_URI=postgres://nanocloud@postgres/nanocloud?sslmode=disable
 restart: always
 container_name: "history-module"

iaas-module:
 dockerfile: Dockerfile-iaas
 build: .
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - API_URL=http://apiiaas-module
  - API_PORT=8082
 restart: always
 container_name: "iaas-module"

apiiaas-module:
 dockerfile: Dockerfile-apiiaas
 build: .
 environment:
  - NANOCLOUD_DIR=/var/lib/nanocloud
  - API_PORT=8082
 volumes:
  - installation_dir:/var/lib/nanocloud/
 restart: always
 container_name: "apiiaas-module"

ldap-module:
 dockerfile: Dockerfile-ldap
 build: .
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - USERNAME=CN=Administrator,CN=Users,DC=intra,DC=localdomain,DC=com
  - PASSWORD=Nanocloud123+
  - SERVER_URL=ldaps://10.20.12.20
 restart: always
 container_name: "ldap-module"

users-module:
 dockerfile: Dockerfile-users
 build: .
 environment:
  - ENV=production
  - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
  - DATABASE_URI=postgres://nanocloud@postgres/nanocloud?sslmode=disable
 restart: always
 container_name: "users-module"
