guacamole-client:
 build: ./
 dockerfile: guacamole-client/Dockerfile
 links:
  - guacamole-server:guacd
  - ambassador:proxy
 volumes:
  - ./guacamole-client/guac_home/guacamole.properties:/etc/guacamole/guacamole.properties
  - ./guacamole-client/guac_home/noauth-config.xml:/etc/guacamole/noauth-config.xml
guacamole-server:
 image: glyptodon/guacd
nanocloud-backend:
 build: ./
 dockerfile: nanocloud-backend/Dockerfile
 links:
  - guacamole-client:guacamole
 volumes:
  - ./nanocloud-backend/conf/config.json:/opt/conf/config.json
  - ./nanocloud-backend/conf/ldaprc:/etc/ldap/ldap.conf:ro
  - ./nanocloud-backend/conf/ad2012.cer:/opt/conf/ad2012.cer:ro
 volumes_from:
  - guacamole-client
proxy:
 image: nginx
 volumes:
  - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  - ./nginx/conf/certificates:/etc/nginx/ssl/:ro
 links:
  - nanocloud-backend:haptic
  - ambassador:guacamole-client
 ports:
  - 80:80
  - 443:443
 
ambassador:
 image: cpuguy83/docker-grand-ambassador
 volumes:
 - "/var/run/docker.sock:/var/run/docker.sock"
 command: "-name dockerfiles_guacamole-client_1 -name dockerfiles_proxy_1 "